import { z } from 'zod';
declare const configSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    API_PORT: z.ZodDefault<z.ZodNumber>;
    API_HOST: z.ZodDefault<z.ZodString>;
    WEB_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    DYNAMIC_ENVIRONMENT_ID: z.ZodString;
    DYNAMIC_PUBLIC_KEY: z.ZodString;
    TRADING_KEY_ENCRYPTION_KEY: z.ZodString;
    POLYMARKET_CLOB_API_URL: z.ZodDefault<z.ZodString>;
    POLYMARKET_GAMMA_API_URL: z.ZodDefault<z.ZodString>;
    POLYMARKET_DATA_API_URL: z.ZodDefault<z.ZodString>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    API_PORT: number;
    API_HOST: string;
    WEB_URL: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    DYNAMIC_ENVIRONMENT_ID: string;
    DYNAMIC_PUBLIC_KEY: string;
    TRADING_KEY_ENCRYPTION_KEY: string;
    POLYMARKET_CLOB_API_URL: string;
    POLYMARKET_GAMMA_API_URL: string;
    POLYMARKET_DATA_API_URL: string;
    RATE_LIMIT_MAX: number;
    RATE_LIMIT_WINDOW_MS: number;
}, {
    DATABASE_URL: string;
    DYNAMIC_ENVIRONMENT_ID: string;
    DYNAMIC_PUBLIC_KEY: string;
    TRADING_KEY_ENCRYPTION_KEY: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    API_PORT?: number | undefined;
    API_HOST?: string | undefined;
    WEB_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    POLYMARKET_CLOB_API_URL?: string | undefined;
    POLYMARKET_GAMMA_API_URL?: string | undefined;
    POLYMARKET_DATA_API_URL?: string | undefined;
    RATE_LIMIT_MAX?: number | undefined;
    RATE_LIMIT_WINDOW_MS?: number | undefined;
}>;
export type Config = z.infer<typeof configSchema>;
export declare function getConfig(): Config;
export {};
//# sourceMappingURL=config.d.ts.map